# Generated by Django 2.2.2 on 2019-06-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('total_t', models.CharField(max_length=50)),
                ('total_f', models.CharField(max_length=50)),
                ('percentaje_t', models.CharField(max_length=50)),
                ('percentaje_f', models.CharField(max_length=50)),
            ],
        ),
    ]
