# Generated by Django 2.2.2 on 2019-06-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_analisis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', models.IntegerField(default=0)),
            ],
        ),
    ]
