# Generated by Django 2.2.2 on 2019-06-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_cont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='percentaje_f',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='percentaje_t',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='total_f',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='total_t',
            field=models.FloatField(max_length=50),
        ),
    ]
